name: work_timer_v3
description: "Track your time, achieve your goals. Productivity timer with statistics and goal tracking."
publish_to: 'none'

version: 1.0.6+6




environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  image_picker: ^1.1.2
  fl_chart: ^0.69.0
  share_plus: ^10.0.0   # ⬅️ DODANE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/

generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/wst_icon_512.png"
  adaptive_icon_background: "#5E35B1"
  adaptive_icon_foreground: "assets/wst_icon_512.png"
  min_sdk_android: 21
